---
title: "Figure TikTok dataset"
---

```{r}
library(tidyverse)
library(janitor)
library(ggridges)
library(ggtext)
library(scales)
library(fmsb)
library(tidytext)
```


```{r}
tiktok <- read_csv("./../data/raw/tiktok.csv") %>%
  clean_names() %>%
  select(
    followers, likes, videos_count,
    awg_engagement_rate, like_engagement_rate, comment_engagement_rate,
    predicted_lang, region,
    biography, signature, top_videos
  ) %>%
  mutate(across(where(is.character), na_if, "")) %>%
  drop_na() %>%
  distinct()
```
```{r}
tiktok <- tiktok %>%
  mutate(is_viral = ifelse(awg_engagement_rate > median(awg_engagement_rate), 
                           "Viral", "Non-Viral")) %>%
  mutate(is_viral = factor(is_viral, levels = c("Non-Viral", "Viral")))
```

```{r}
library(ggwordcloud)

custom_stop <- c("tiktok", "video", "follow")

hook_words <- tiktok |>
  select(is_viral, signature) |>
  unnest_tokens(word, signature) |>
  anti_join(stop_words, by="word") |>
  filter(!word %in% custom_stop) |>
  group_by(is_viral, word) |>
  summarise(n = n(), .groups="drop") |>
  group_by(is_viral) |>
  slice_max(n, n = 15)

#ggplot(hook_words, aes(label = word, size = n)) +
  #geom_text_wordcloud() +
  #scale_size_area(max_size = 20) +
  #theme_minimal() +
  #labs(title = "Word Cloud: Viral Videos (Caption Language)")

 ggplot(hook_words, aes(label = word, size = n, color = n, alpha = n)) +
  geom_text_wordcloud(
    rm_outliers = TRUE,
    eccentricity = 1.5,
    grid_size = 10,
    shape = "circle"
  ) +
  scale_size_area(max_size = 20, name = "Word Frequency") +
  scale_alpha(range = c(0.3, 1),name = "Frequency (Transparency)") +         
  scale_color_viridis_c(option = "C", name = "Frequency (Color)") +
  guides(
    size = guide_legend(),
    color = guide_colorbar(),
    alpha = guide_legend()
  ) +
  labs(
    title = "Most Common Words in Viral TikTok Captions",
    subtitle = "Size, color, and transparency all represent word frequency",
    caption = "Data: TikTok dataset",
    x = NULL,
    y = NULL
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 18),
    legend.position = "right",
    panel.grid = element_blank())

ggplot(hook_words, aes(n, fct_reorder(word, n), fill = is_viral)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~is_viral, scales = "free_y") +
  labs(
    title = "Top Words in Viral vs Non-Viral TikTok Captions",
    x = "Frequency",
    y = ""
  ) +
  theme_minimal(base_size = 10)
```




